### ISSUE TITLE
getting error while running PrediXcan.py for Predicting/Imputing Expression

### ISSUE THREAD

**Issue by tushardave26** [hriordan/PrediXcan#11]
Hello Authors,

I am facing an error while I am running PrediXcan.py script for Predicting/Imputing Expression. Below is my command line:

python ./PrediXcan.py --predict --dosages dosages --dosages_prefix chr --sample dosages/sample.txt -- weights Liver_LASSO.db --output_dir .

Below are first 3 lines of my sample.txt file:
10878 10878 0 0 0 0 -9
11655 11655 0 0 0 0 -9
12201 12201 0 0 0 0 -9

Below is the log file content:

2016-04-14 14:06:55.609509 Preloading weights...
2016-04-14 14:06:56.201847 Processing chr1.dosage.data.txt.gz
2016-04-14 14:24:10.396559 Processing chr10.dosage.data.txt.gz
2016-04-14 14:35:32.422774 Processing chr11.dosage.data.txt.gz
2016-04-14 14:46:11.936055 Processing chr12.dosage.data.txt.gz
2016-04-14 14:56:42.306676 Processing chr13.dosage.data.txt.gz
2016-04-14 15:04:40.451957 Processing chr14.dosage.data.txt.gz
2016-04-14 15:12:00.289541 Processing chr15.dosage.data.txt.gz
2016-04-14 15:18:19.583822 Processing chr16.dosage.data.txt.gz
2016-04-14 15:25:31.726997 Processing chr17.dosage.data.txt.gz
2016-04-14 15:31:46.137181 Processing chr18.dosage.data.txt.gz
2016-04-14 15:38:07.463976 Processing chr19.dosage.data.txt.gz
2016-04-14 15:43:57.293840 Processing chr2.dosage.data.txt.gz
2016-04-14 16:01:55.391602 Processing chr20.dosage.data.txt.gz
2016-04-14 16:07:00.779805 Processing chr21.dosage.data.txt.gz
2016-04-14 16:10:12.819881 Processing chr22.dosage.data.txt.gz
2016-04-14 16:13:29.788277 Processing chr3.dosage.data.txt.gz
2016-04-14 16:28:40.400313 Processing chr4.dosage.data.txt.gz
2016-04-14 16:44:31.586482 Processing chr5.dosage.data.txt.gz
2016-04-14 16:58:26.106604 Processing chr6.dosage.data.txt.gz
2016-04-14 17:12:43.945125 Processing chr7.dosage.data.txt.gz
2016-04-14 17:25:40.343552 Processing chr8.dosage.data.txt.gz
2016-04-14 17:38:02.067445 Processing chr9.dosage.data.txt.gz
Traceback (most recent call last):
  File "/data/ssalimi/packages/PrediXcan/Software/PrediXcan.py", line 198, in <module>
    main()
  File "/data/ssalimi/packages/PrediXcan/Software/PrediXcan.py", line 181, in main
    transcription_matrix.save(PRED_EXP_FILE)
  File "/data/ssalimi/packages/PrediXcan/Software/PrediXcan.py", line 118, in save
    outfile.write('\t'.join(next(sample_generator)) + '\t' + '\t'.join(map(str, self.D[:,col]))+'\n')
StopIteration

I am not sure why I am having this error. Can you please help me to understand the issue and also help me to resolve it?

Thanks.

Best,
Tushar

**Comment by ScottPDickinson** [comment]
Hi Tushar,

We'll be closing this thread since we're addressing this in another location.  Also, we have an update to the repository that makes this error less cryptic.  You can find it at hakyimlab/PrediXcan.

Best,
Scott
